### ISSUE TITLE
Missing translation file causes text loss

### ISSUE THREAD

**Issue by eson57** [nephros/peekfilter-button#2]
Latest release took away gui text, which usually happens when app is trying to translate but there is no correct translation file.

![Screen_20230124_001](https://user-images.githubusercontent.com/2996154/214234074-f70f82a4-d66a-4cf9-8d67-8970bc0803d4.png)

Looks fine with correct translation file though...
![copy-25Screen_20230124_002](https://user-images.githubusercontent.com/2996154/214241729-ad217d56-5e50-44b6-857f-744f1ac5b2ec.png)

**Comment by nephros** [comment]
Thank you, that is embarassing. 8-)

**Comment by nephros** [comment]
Just to be clear, the first screenshot is what it looks like when using a locale other than (at the moment) DE and EN, correct?

**Comment by eson57** [comment]
Yes, that is correct.

tisdag den 24 januari 2023 skrev Peter G.:
> Just to be clear, the first screenshot is what it looks like when using a locale other than (at the moment) DE and EN, correct?
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/nephros/peekfilter-button/issues/2#issuecomment-1401765974
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***

-- 
Sent from my Sailfish device

**Comment by nephros** [comment]
Could you kindly test if [0.9.6+git2](https://build.merproject.org/package/show/sailfishos:chum:testing/peekfilter-button) fixes this?

**Comment by eson57** [comment]
It did! 👍🏻
